# MySQL. Versions 5.5.8 and up are supported.
#

default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: RecipApp_development

test:
  <<: *default
  database: RecipApp_test
  host: <%= ENV.fetch("APP_DATABASE_HOST") { 'db' } %>

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
